export const ADD_DEVICE_REQUEST = "ADD_DEVICE_REQUEST";
export const ADD_DEVICE_SUCCESS = "ADD_DEVICE_SUCCESS";
export const ADD_DEVICE_FAILURE = "ADD_DEVICE_FAILURE";

export const UPDATE_DEVICE_REQUEST = "UPDATE_DEVICE_REQUEST";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_FAILURE = "UPDATE_DEVICE_FAILURE";

export const GET_DEVICE_REQUEST = "GET_DEVICE_REQUEST";
export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
export const GET_DEVICE_FAILURE = "GET_DEVICE_FAILURE";

export const DELETE_DEVICE_REQUEST = "DELETE_DEVICE_REQUEST";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const DELETE_DEVICE_FAILURE = "DELETE_DEVICE_FAILURE";

export const GETBYID_DEVICE_REQUEST = "GETBYID_DEVICE_REQUEST";
export const GETBYID_DEVICE_SUCCESS = "GETBYID_DEVICE_SUCCESS";
export const GETBYID_DEVICE_FAILURE = "GETBYID_DEVICE_FAILURE";

export const GET_VEHICLE_REQUEST = "GET_VEHICLE_REQUEST";
export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS";
export const GET_VEHICLE_FAILURE = "GET_VEHICLE_FAILURE";

export const ADD_VEHICLE_REQUEST = "ADD_VEHICLE_REQUEST";
export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";
export const ADD_VEHICLE_FAILURE = "ADD_VEHICLE_FAILURE";

export const EDIT_VEHICLE_REQUEST = "EDIT_VEHICLE_REQUEST";
export const EDIT_VEHICLE_SUCCESS = "EDIT_VEHICLE_SUCCESS";
export const EDIT_VEHICLE_FAILURE = "EDIT_VEHICLE_FAILURE";

export const DELETE_VEHICLE_REQUEST = "DELETE_VEHICLE_REQUEST";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAILURE = "DELETE_VEHICLE_FAILURE";

export const GETBYID_VEHICLE_REQUEST = "GETBYID_VEHICLE_REQUEST";
export const GETBYID_VEHICLE_SUCCESS = "GETBYID_VEHICLE_SUCCESS";
export const GETBYID_VEHICLE_FAILURE = "GETBYID_VEHICLE_FAILURE";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

export const EDIT_CUSTOMER_REQUEST = "EDIT_CUSTOMER_REQUEST";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";

export const GETBTID_CUSTOMER_REQUEST = "GETBYID_CUSTOMER_REQUEST";
export const GETBTID_CUSTOMER_SUCCESS = "GETBYID_CUSTOMER_SUCCESS";
export const GETBTID_CUSTOMER_FAILURE = "GETBYID_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";

export const GETBYID_CUSTOMER_REQUEST = "GETBYID_CUSTOMER_REQUEST";
export const GETBYID_CUSTOMER_SUCCESS = "GETBYID_CUSTOMER_SUCCESS";
export const GETBYID_CUSTOMER_FAILURE = "GETBYID_CUSTOMER_FAILURE";

export const GET_IoT_REQUEST = "GET_IoT_REQUEST";
export const GET_IoT_SUCCESS = "GET_IoT_SUCCESS";
export const GET_IoT_FAILURE = "GET_IoT_FAILURE";

export const GET_ECU_REQUEST = "GET_ECU_REQUEST";
export const GET_ECU_SUCCESS = "GET_ECU_SUCCESS";
export const GET_ECU_FAILURE = "GET_ECU_FAILURE";

export const GET_CUSTOMERVEHICLE_REQUEST = "GET_CUSTOMERVEHICLE_REQUEST";
export const GET_CUSTOMERVEHICLE_SUCCESS = "GET_CUSTOMERVEHICLE_SUCCESS";
export const GET_CUSTOMERVEHICLE_FAILURE = "GET_CUSTOMERVEHICLE_FAILURE";

export const GETBYID_MASTERCUSTOMER_REQUEST = "GETBYID_MASTERCUSTOMER_REQUEST";
export const GETBYID_MASTERCUSTOMER_SUCCESS = "GETBYID_MASTERCUSTOMER_SUCCESS";
export const GETBYID_MASTERCUSTOMER_FAILURE = "GETBYID_MASTERCUSTOMER_FAILURE";

export const EDIT_MASTERCUSTOMER_REQUEST = "EDIT_MASTERCUSTOMER_REQUEST";
export const EDIT_MASTERCUSTOMER_SUCCESS = "EDIT_MASTERCUSTOMER_SUCCESS";
export const EDIT_MASTERCUSTOMER_FAILURE = "EDIT_MASTERCUSTOMER_FAILURE";

export const ADD_MASTERCUSTOMER_REQUEST = "ADD_MASTERCUSTOMER_REQUEST";
export const ADD_MASTERCUSTOMER_SUCCESS = "ADD_MASTERCUSTOMER_SUCCESS";
export const ADD_MASTERCUSTOMER_FAILURE = "ADD_MASTERCUSTOMER_FAILURE";
